### ISSUE TITLE
Firefox is OpenSource, but not labelled or linked

### ISSUE THREAD

**Issue by RyanPattison** [VoLuong/Awesome-Ubuntu-Linux#10]
Firefox is an OpenSource/Free Software browser, released under the [Mozilla Public License (MPL)](https://www.mozilla.org/en-US/MPL/).
The [latest code](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Downloading_Source_Archives)  can be found on line.

**Comment by VoLuong** [comment]
Thank you. I will fix that. Actually there are many apps that lack opensource icon because I havent yet found out where the codes are host. Thank you
