### ISSUE TITLE
Some new apps and tools

### ISSUE THREAD

**Issue by ank91** [VoLuong/Awesome-Ubuntu-Linux#13]
Hi, i don't have enough time to make a PR. 
Please consider adding these if you like.

----------

**Audio**
[Audio Recorder](https://launchpad.net/~audio-recorder/+archive/ubuntu/ppa)

**Data Backup and Recovery**
[CloneZilla](http://clonezilla.org/)

**Desktop customization**
[Yosembiance Theme](https://github.com/bsundman/Yosembiance)
[Irradiance Theme](https://github.com/bsundman/Irradiance)

**Email**
[MailNag](https://github.com/pulb/mailnag)

**Internet**
[Opera](http://www.opera.com/download)

**Security**
[guFw](http://gufw.org/)

**Sharing Files**
[uGet](http://ugetdm.com/)

**Utilities**
[xfburn](https://apps.ubuntu.com/cat/applications/precise/xfburn/)
[unetbootin](http://unetbootin.github.io/linux_download.html)
[WinUSB](http://www.webupd8.org/2016/06/make-bootable-windows-10-usb-install.html)
[grub-customizer](https://launchpad.net/grub-customizer)
[selene-media-encoder](http://www.teejeetech.in/p/selene-media-encoder.html)
[muPDF](http://mupdf.com/)
[PeaZip](http://www.peazip.org/peazip-linux.html)

**Comment by VoLuong** [comment]
No worry. I will sure check out them and add all of them if no problems occur! 
Thank you very much.
You dont even need to open a PR. Your time spent here writing this issue is priceless help to me. 
Again, thank you.

**Comment by VoLuong** [comment]
I will add you to the contributor list, btw

**Comment by ank91** [comment]
@VoLuong 

Please correct the typo in **Kit3Qt** it should be **Kid3Q1**.
Replace the _t_ with _d_

Thanks

**Comment by VoLuong** [comment]
Will fix right now.
