### ISSUE TITLE
Add Filezilla

### ISSUE THREAD

**Issue by shakib609** [VoLuong/Awesome-Ubuntu-Linux#33]
Consider adding this one.

**Sharing Files**
[Filezillla](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiHsOWytrfOAhUKto8KHdfZC1MQFggeMAA&url=https%3A%2F%2Ffilezilla-project.org%2F&usg=AFQjCNGk29GabeehesFbZH8JF3yxkKf73A&sig2=RYZK3Q-wOrgibYK2QqUA_A)

**Comment by VoLuong** [comment]
Thank you. I will check it out first. My next commit will include it if possible ;)

**Comment by VoLuong** [comment]
Done added

**Comment by shakib609** [comment]
:+1:
