### ISSUE TITLE
Games additon

### ISSUE THREAD

**Issue by jakub-olczyk** [VoLuong/Awesome-Ubuntu-Linux#34]
Consider addition of games from this list :)

* [Minetest](http://www.minetest.net/) - open-source Minecraft written is C++ (uses less resources) and includes modding API.
* [Warzone 2100](https://wz2100.net/) - open-source real-time strategy/real-time tactics game.
* [SuperTuxKart](https://supertuxkart.net/Main_Page) - 3D open-source arcade racer with a variety characters, tracks, and modes to play.

**Comment by VoLuong** [comment]
Thank you. I will check them out and add them to tthe list ;)

**Comment by VoLuong** [comment]
I added all of them just now
